language: android

jdk:
  - oraclejdk8

before_install:
  # Install SDK license so Android Gradle plugin can install deps.
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" > "$ANDROID_HOME/licenses/android-sdk-license"
  # Install the system image
  - sdkmanager "system-images;android-21;default;armeabi-v7a"
  # Create and start emulator for the script. Meant to race the install task.
  - echo no | avdmanager create avd --force -n test -k "system-images;android-21;default;armeabi-v7a"
  - mksdcard -l e 512M test-sd.img # Needed for Facebooks screenshot testing.
  - $ANDROID_HOME/emulator/emulator -avd test -sdcard test-sd.img -no-audio -no-window &

install: ./gradlew clean assemble assembleAndroidTest --stacktrace

before_script:
  - android-wait-for-emulator
  - adb shell input keyevent 82

script: ./gradlew check createDebugCoverageReport --stacktrace

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - .buildscript/deploy_snapshot.sh

env:
  global:
    - secure: "5km2ETNz3UF9XoXxIrVdUL9zF4yA+WAKLBJWGYSMv5Z8Vw23veIGSgf2beVTVVLqHExS385MVkK20cgr97Y2JYLkrsx8uh+E3u9+Xh+wOgKqdGAWt/de/B8OzDgAMsT22Q4Pb7E4lNALD+ERgoQRkKpqbye5gijU6yD1rilFAGRq45cgEUB1ogm/YlMZSs2sIsYzvBWBA367ySJpnN8eKuKFpRvuoyUCyAvC/Ih4vWZE+dyxO/dMAVFOEkgoPpFcN+PvxfcBx6ZUaRXb3ZifgcOrYEb9ARWuxJ2Qm2dksZztxY36PLtAwGX8fi3k8zGOdat/lxj+QKqS8/wppyNIA+Doi0rZrszblDGjAlwT86gUile+UNth+I3hqQV7i8EzcdZpBHOsls9CstUH/bmFEFugCxIDBktYWONOamwHHUf9Rl1FEnVcKEU4vgtag8EIO6+Q4PWetFAC+3nubJVy7eM/y8hs645aEHEbByGrxDhBc+iSANn9cFKU+RcOnncsIDpTQkBmVeLLbUqTbsUJmwOIuJClQ1eQc4CnRn1THlA67Fk5dYhYKuYQjU5ny2lbbag0tvteA6pfvlixgcE6lxxWzdA1M2WmTgT/oL7SGTokLR7BtwCeRZnM+pMn60uQXGYi4wK7sfwBPs8GsXbk9c6r1X5qfHaHXxesSgdu4ZQ="
    - secure: "W5JEBBMn9v+8KmY4FkSzEHDpP01h9JULPXf/iPh5n8kEsjIO7HLjNzhkrA0w3gfzYG+ZOEB6gAi5akHYGEdP3qKa0rEhbjjvFPW2z3XiPkWNdEArAFboUkmpNEuSgpAhrjK/69bhF/b/3FUWoyh0Hc2w5kii8/quGYQHisGcSqCqDZqJXdHAo1h3gIVzZKp5GfLgd2Lj5r4BSj1n1mIH3Q94/jONJ1hroItwUkxB5lFp2a4MWCbD+kHy3tQi4pWzXcUpX+z/d6G1hFFFYeQ0Ps6q1At8MDv2V5012nXbYZ4CJDaAu2eBcAIinoP2DtxikhAHqL9pPe9/+RWrGBA4nFALvxOZX0GaDAobAkOhXkZmu2hvshGQi5+uPbCxlMuOTnwf+v8waqNX3PSCc2xZnGc/xF0bBJwx4IfaWir9hRNJonY5qQZapev7kFoKjwsErzazNYlpJVtP3LxLTUsE94pW/tZsqYdoS8+lDkgQijr6YuNut29UQq6WHgBMMDqVjAwErcZZdLKqBbiacFF4Ki/JRV3+HWw6W05XxQpba/NK4vxlWV/QKrXhC5d1Ptjzvs8fpRqLcTOVMhcBGwv08Wj9pIYeX83R3lz8mCVnNXJbJvWKDfVdtrKyVfIIclg6HcjlTVt/v1qHVXj76snRiuta6gzz6xAIESOxnG5FgQc="

branches:
  except:
    - gh-pages

notifications:
  email: false

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
